CREATE TABLE IF NOT EXISTS users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username character varying(50) NOT NULL,
    password character varying(255) DEFAULT NULL,
    UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS triggers (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    triggers json NOT NULL,
    response text NOT NULL,
    user_id integer,
    CONSTRAINT fk_user FOREIGN KEY (user_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL
        NOT VALID
);
